kr_adjust_stack_sizes = true
kr_optimization_tech_card_name = "space-science-pack"

require("util")
require("prototypes.fluids")
require("prototypes.menu-simulations")

require("prototypes.buildings.advanced-assembling-machine")
require("prototypes.buildings.advanced-chemical-plant")
require("prototypes.buildings.advanced-furnace")
require("prototypes.buildings.advanced-lab")
require("prototypes.buildings.advanced-steam-turbine")
require("prototypes.buildings.air-purifier")
require("prototypes.buildings.antimatter-reactor")
require("prototypes.buildings.atmospheric-condenser")
require("prototypes.buildings.big-roboport")
require("prototypes.buildings.bio-lab")
require("prototypes.buildings.crusher")
require("prototypes.buildings.electric-mining-drill-mk2")
require("prototypes.buildings.electrolysis-plant")
require("prototypes.buildings.energy-storage")
require("prototypes.buildings.express-loader")
require("prototypes.buildings.filtration-plant")
require("prototypes.buildings.flare-stack")
require("prototypes.buildings.fuel-refinery")
require("prototypes.buildings.fusion-reactor")
require("prototypes.buildings.gas-power-station")
require("prototypes.buildings.greenhouse")
require("prototypes.buildings.intergalactic-transceiver")
require("prototypes.buildings.matter-associator")
require("prototypes.buildings.matter-plant")
require("prototypes.buildings.planetary-teleporter")
require("prototypes.buildings.quantum-computer")
require("prototypes.buildings.research-server")
require("prototypes.buildings.rocket-turret")
require("prototypes.buildings.singularity-beacon")
require("prototypes.buildings.singularity-lab")
require("prototypes.buildings.small-roboport")
require("prototypes.buildings.stabilizer-charging-station")
require("prototypes.buildings.steel-pipe")
require("prototypes.buildings.steel-pipe-to-ground")
require("prototypes.buildings.steel-pump")
require("prototypes.buildings.superior-inserter")
require("prototypes.buildings.superior-long-inserter")
require("prototypes.buildings.superior-splitter")
require("prototypes.buildings.superior-substation")
require("prototypes.buildings.superior-transport-belt")
require("prototypes.buildings.superior-underground-belt")
require("prototypes.buildings.tesla-coil")
require("prototypes.buildings.wind-turbine")

require("prototypes.categories.item-subgroups")
require("prototypes.categories.recipe-categories")

require("prototypes.equipment.cargo-expansion")

require("prototypes.items.tech-cards")

require("prototypes.recipes.atmosphere-condensation")
require("prototypes.recipes.crafting")
require("prototypes.recipes.crushing")
require("prototypes.recipes.growing")
require("prototypes.recipes.nuclear-fusion")
require("prototypes.recipes.smelting")
require("prototypes.recipes.tech-cards")
require("prototypes.recipes.cryogenics")
require("prototypes.recipes.electronics")
require("prototypes.recipes.metallurgy")
require("prototypes.recipes.organic")

require("prototypes.technologies.utility-science-pack")
require("prototypes.technologies.advanced-tech-card")
require("prototypes.technologies.matter-tech-card")
require("prototypes.technologies.singularity-tech-card")
require("prototypes.technologies.space-age")
