data:extend({
	{
		type = "technology",
		name = "kr-matter-processing",
		icon = "__Krastorio2Assets__/technologies/matter-processing.png",
		icon_size = 256,
		order = "g-e-d",
		unit = {
			time = 45,
			count = 2000,
			ingredients = {
				{ "production-science-pack", 1 },
				{ "utility-science-pack", 1 },
				{ kr_optimization_tech_card_name, 1 },
				{ "metallurgic-science-pack", 1 },
				{ "agricultural-science-pack", 1 },
				{ "electromagnetic-science-pack", 1 },
				{ "kr-advanced-tech-card", 1 },
				{ "kr-matter-tech-card", 1 },
			},
		},
		prerequisites = { "kr-energy-control-unit", "kr-matter-tech-card" },
		effects = {
			{ type = "unlock-recipe", recipe = "kr-matter-plant" },
			{ type = "unlock-recipe", recipe = "kr-matter-associator" },
			{ type = "unlock-recipe", recipe = "kr-stabilizer-charging-station" },
			{ type = "unlock-recipe", recipe = "kr-matter-stabilizer" },
			{ type = "unlock-recipe", recipe = "kr-charged-matter-stabilizer" },
		},
	},

	--Nauvis

	{
		type = "technology",
		name = "kr-matter-coal-processing",
		icon = "__Krastorio2Assets__/technologies/matter-coal.png",
		icon_size = 256,
		order = "g-e-e",
		unit = {
			time = 45,
			count = 1500,
			ingredients = {
				{ "production-science-pack", 1 },
				{ "utility-science-pack", 1 },
				{ kr_optimization_tech_card_name, 1 },
				{ "kr-advanced-tech-card", 1 },
				{ "kr-matter-tech-card", 1 },
			},
		},
		prerequisites = { "kr-matter-processing" },
		effects = {},
	},
	{
		type = "technology",
		name = "kr-matter-copper-processing",
		icon = "__Krastorio2Assets__/technologies/matter-copper.png",
		icon_size = 256,
		order = "g-e-e",
		unit = {
			time = 45,
			count = 2000,
			ingredients = {
				{ "production-science-pack", 1 },
				{ "utility-science-pack", 1 },
				{ kr_optimization_tech_card_name, 1 },
				{ "kr-advanced-tech-card", 1 },
				{ "kr-matter-tech-card", 1 },
			},
		},
		prerequisites = { "kr-matter-processing" },
		effects = {},
	},
	{
		type = "technology",
		name = "kr-matter-iron-processing",
		icon = "__Krastorio2Assets__/technologies/matter-iron.png",
		icon_size = 256,
		order = "g-e-e",
		unit = {
			time = 45,
			count = 2000,
			ingredients = {
				{ "production-science-pack", 1 },
				{ "utility-science-pack", 1 },
				{ kr_optimization_tech_card_name, 1 },
				{ "kr-advanced-tech-card", 1 },
				{ "kr-matter-tech-card", 1 },
			},
		},
		prerequisites = { "kr-matter-processing" },
		effects = {},
	},
	{
		type = "technology",
		name = "kr-matter-oil-processing",
		icon = "__Krastorio2Assets__/technologies/matter-oil.png",
		icon_size = 256,
		order = "g-e-e",
		unit = {
			time = 45,
			count = 2500,
			ingredients = {
				{ "production-science-pack", 1 },
				{ "utility-science-pack", 1 },
				{ kr_optimization_tech_card_name, 1 },
				{ "kr-advanced-tech-card", 1 },
				{ "kr-matter-tech-card", 1 },
			},
		},
		prerequisites = { "kr-matter-processing" },
		effects = {},
	},
	{
		type = "technology",
		name = "kr-matter-rare-metals-processing",
		icon = "__Krastorio2Assets__/technologies/matter-rare-metals.png",
		icon_size = 256,
		order = "g-e-e",
		unit = {
			time = 45,
			count = 5000,
			ingredients = {
				{ "production-science-pack", 1 },
				{ "utility-science-pack", 1 },
				{ kr_optimization_tech_card_name, 1 },
				{ "kr-advanced-tech-card", 1 },
				{ "kr-matter-tech-card", 1 },
			},
		},
		prerequisites = { "kr-matter-processing" },
		effects = {},
	},
	{
		type = "technology",
		name = "kr-matter-stone-processing",
		icon = "__Krastorio2Assets__/technologies/matter-stone.png",
		icon_size = 256,
		order = "g-e-e",
		unit = {
			count = 1000,
			ingredients = {
				{ "production-science-pack", 1 },
				{ "utility-science-pack", 1 },
				{ kr_optimization_tech_card_name, 1 },
				{ "kr-advanced-tech-card", 1 },
				{ "kr-matter-tech-card", 1 },
			},
			time = 45,
		},
		prerequisites = { "kr-matter-processing" },
		effects = {},
	},
	{
		type = "technology",
		name = "kr-matter-uranium-processing",
		icon = "__Krastorio2Assets__/technologies/matter-uranium.png",
		icon_size = 256,
		order = "g-e-e",
		unit = {
			time = 45,
			count = 5000,
			ingredients = {
				{ "production-science-pack", 1 },
				{ "utility-science-pack", 1 },
				{ kr_optimization_tech_card_name, 1 },
				{ "kr-advanced-tech-card", 1 },
				{ "kr-matter-tech-card", 1 },
			},
		},
		prerequisites = { "kr-matter-processing" },
		effects = {},
	},
	{
		type = "technology",
		name = "kr-matter-water-processing",
		icon = "__Krastorio2Assets__/technologies/matter-water.png",
		icon_size = 256,
		order = "g-e-e",
		unit = {
			time = 45,
			count = 500,
			ingredients = {
				{ "production-science-pack", 1 },
				{ "utility-science-pack", 1 },
				{ kr_optimization_tech_card_name, 1 },
				{ "kr-advanced-tech-card", 1 },
				{ "kr-matter-tech-card", 1 },
			},
		},
		prerequisites = { "kr-matter-processing" },
		effects = {},
	},

	--Singularity

	{
		type = "technology",
		name = "kr-matter-minerals-processing",
		icon = "__Krastorio2Assets__/technologies/matter-minerals.png",
		icon_size = 256,
		order = "g-e-e",
		unit = {
			time = 45,
			count = 20000,
			ingredients = {
				{ "production-science-pack", 1 },
				{ "utility-science-pack", 1 },
				{ kr_optimization_tech_card_name, 1 },
				{ "kr-advanced-tech-card", 1 },
				{ "kr-matter-tech-card", 1 },
				{ "kr-singularity-tech-card", 1 },
			},
		},
		prerequisites = { "kr-matter-processing", "kr-singularity-tech-card" },
		effects = {},
	},

	--Vulcanus

	{
		type = "technology",
		name = "kr-matter-tungsten-processing",
		icons = {
			{ icon = "__Krastorio2Assets__/icons/fluids/matter.png" },
			{ icon = "__space-age__/graphics/icons/tungsten-ore.png", scale = 0.85 },
		},
		icon_size = 256,
		order = "g-e-e",
		unit = {
			time = 45,
			count = 5000,
			ingredients = {
				{ "production-science-pack", 1 },
				{ "utility-science-pack", 1 },
				{ kr_optimization_tech_card_name, 1 },
				{ "metallurgic-science-pack", 1 },
				{ "kr-advanced-tech-card", 1 },
				{ "kr-matter-tech-card", 1 },
			},
		},
		prerequisites = { "kr-matter-processing" },
		effects = {},
	},
	{
		type = "technology",
		name = "kr-matter-calcite-processing",
		icons = {
			{ icon = "__Krastorio2Assets__/icons/fluids/matter.png" },
			{ icon = "__space-age__/graphics/icons/calcite.png", scale = 0.85 },
		},
		icon_size = 256,
		order = "g-e-e",
		unit = {
			time = 45,
			count = 3000,
			ingredients = {
				{ "production-science-pack", 1 },
				{ "utility-science-pack", 1 },
				{ kr_optimization_tech_card_name, 1 },
				{ "metallurgic-science-pack", 1 },
				{ "kr-advanced-tech-card", 1 },
				{ "kr-matter-tech-card", 1 },
			},
		},
		prerequisites = { "kr-matter-processing" },
		effects = {},
	},

	--Fulgora

	{
		type = "technology",
		name = "kr-matter-scrap-processing",
		icons = {
			{ icon = "__Krastorio2Assets__/icons/fluids/matter.png" },
			{ icon = "__space-age__/graphics/icons/scrap.png", scale = 0.85 },
		},
		icon_size = 256,
		order = "g-e-e",
		unit = {
			time = 45,
			count = 10000,
			ingredients = {
				{ "production-science-pack", 1 },
				{ "utility-science-pack", 1 },
				{ kr_optimization_tech_card_name, 1 },
				{ "electromagnetic-science-pack", 1 },
				{ "kr-advanced-tech-card", 1 },
				{ "kr-matter-tech-card", 1 },
			},
		},
		prerequisites = { "kr-matter-processing" },
		effects = {},
	},
	{
		type = "technology",
		name = "kr-matter-holmium-processing",
		icons = {
			{ icon = "__Krastorio2Assets__/icons/fluids/matter.png" },
			{ icon = "__space-age__/graphics/icons/holmium-ore.png", scale = 0.85 },
		},
		icon_size = 256,
		order = "g-e-e",
		unit = {
			time = 45,
			count = 5000,
			ingredients = {
				{ "production-science-pack", 1 },
				{ "utility-science-pack", 1 },
				{ kr_optimization_tech_card_name, 1 },
				{ "electromagnetic-science-pack", 1 },
				{ "kr-advanced-tech-card", 1 },
				{ "kr-matter-tech-card", 1 },
			},
		},
		prerequisites = { "kr-matter-processing" },
		effects = {},
	},

	--Aquilo

	{
		type = "technology",
		name = "kr-matter-fluorine-processing",
		icons = {
			{ icon = "__Krastorio2Assets__/icons/fluids/matter.png" },
			{ icon = "__space-age__/graphics/icons/fluid/fluorine.png", scale = 0.85 },
		},
		icon_size = 256,
		order = "g-e-e",
		unit = {
			time = 45,
			count = 5000,
			ingredients = {
				{ "production-science-pack", 1 },
				{ "utility-science-pack", 1 },
				{ kr_optimization_tech_card_name, 1 },
				{ "cryogenic-science-pack", 1 },
				{ "kr-advanced-tech-card", 1 },
				{ "kr-matter-tech-card", 1 },
			},
		},
		prerequisites = { "kr-matter-processing", "cryogenic-science-pack" },
		effects = {},
	},
	{
		type = "technology",
		name = "kr-matter-lithium-brine-processing",
		icons = {
			{ icon = "__Krastorio2Assets__/icons/fluids/matter.png" },
			{ icon = "__space-age__/graphics/icons/fluid/lithium-brine.png", scale = 0.85 },
		},
		icon_size = 256,
		order = "g-e-e",
		unit = {
			time = 45,
			count = 5000,
			ingredients = {
				{ "production-science-pack", 1 },
				{ "utility-science-pack", 1 },
				{ kr_optimization_tech_card_name, 1 },
				{ "cryogenic-science-pack", 1 },
				{ "kr-advanced-tech-card", 1 },
				{ "kr-matter-tech-card", 1 },
			},
		},
		prerequisites = { "kr-matter-processing", "cryogenic-science-pack" },
		effects = {},
	},
})
