data:extend({
	{
		type = "recipe",
		name = "kr-advanced-chemical-plant",
		energy_required = 30,
		enabled = false,
		additional_categories = { "kr-advanced-chemistry" },
		ingredients = {
			{ type = "item", name = "processing-unit", amount = 20 },
			{ type = "item", name = "kr-imersium-beam", amount = 20 },
			{ type = "item", name = "kr-rare-metals", amount = 80 },
			{ type = "item", name = "kr-electronic-components", amount = 40 },
			{ type = "item", name = "carbon-fiber", amount = 20 },
			{ type = "item", name = "kr-steel-pipe", amount = 10 },
		},
		results = { { type = "item", name = "kr-advanced-chemical-plant", amount = 1 } },
	},
	{
		type = "recipe",
		name = "kr-advanced-furnace",
		category = "metallurgy-or-assembling",
		energy_required = 30,
		enabled = false,
		ingredients = {
			{ type = "item", name = "kr-imersium-beam", amount = 40 },
			{ type = "item", name = "tungsten-plate", amount = 40 },
			{ type = "item", name = "foundry", amount = 3 },
			{ type = "item", name = "kr-energy-control-unit", amount = 10 },
		},
		results = { { type = "item", name = "kr-advanced-furnace", amount = 1 } },
	},
	{
		type = "recipe",
		name = "kr-energy-storage",
		energy_required = 30,
		category = "electronics",
		enabled = false,
		ingredients = {
			{ type = "item", name = "processing-unit", amount = 10 },
			{ type = "item", name = "supercapacitor", amount = 30 },
			{ type = "item", name = "kr-rare-metals", amount = 50 },
			{ type = "item", name = "kr-energy-control-unit", amount = 50 },
		},
		results = { { type = "item", name = "kr-energy-storage", amount = 1 } },
	},
	{
		type = "recipe",
		name = "kr-quantum-computer",
		energy_required = 120,
		enabled = false,
		category = "cryogenics",
		ingredients = {
			{ type = "item", name = "kr-rare-metals", amount = 50 },
			{ type = "item", name = "kr-ai-core", amount = 50 },
			{ type = "item", name = "steel-plate", amount = 100 },
			{ type = "item", name = "quantum-processor", amount = 100 },
			{ type = "fluid", name = "fluoroketone-cold", amount = 100 },
		},
		results = { { type = "item", name = "kr-quantum-computer", amount = 1 } },
	},
	{
		type = "recipe",
		name = "kr-rocket-turret",
		enabled = false,
		energy_required = 20,
		ingredients = {
			{ type = "item", name = "rocket-launcher", amount = 6 },
			{ type = "item", name = "kr-steel-beam", amount = 10 },
			{ type = "item", name = "kr-rare-metals", amount = 20 },
			{ type = "item", name = "processing-unit", amount = 20 },
			{ type = "item", name = "carbon-fiber", amount = 40 },
			{ type = "item", name = "low-density-structure", amount = 10 },
		},
		results = { { type = "item", name = "kr-rocket-turret", amount = 1 } },
	},
	{
		type = "recipe",
		name = "kr-superior-splitter",
		category = "metallurgy",
		energy_required = 2,
		enabled = false,
		ingredients = {
			{ type = "item", name = "turbo-splitter", amount = 1 },
			{ type = "item", name = "kr-imersium-gear-wheel", amount = 4 },
			{ type = "item", name = "kr-ai-core", amount = 1 },
		},
		results = { { type = "item", name = "kr-superior-splitter", amount = 1 } },
	},
	{
		type = "recipe",
		name = "kr-superior-substation",
		energy_required = 1,
		category = "electronics",
		enabled = false,
		ingredients = {
			{ type = "item", name = "kr-imersium-beam", amount = 3 },
			{ type = "item", name = "kr-rare-metals", amount = 6 },
			{ type = "item", name = "substation", amount = 1 },
			{ type = "item", name = "processing-unit", amount = 2 },
			{ type = "item", name = "small-lamp", amount = 2 },
		},
		results = { { type = "item", name = "kr-superior-substation", amount = 1 } },
	},
	{
		type = "recipe",
		name = "kr-superior-transport-belt",
		category = "metallurgy",
		energy_required = 0.5,
		enabled = false,
		ingredients = {
			{ type = "item", name = "turbo-transport-belt", amount = 1 },
			{ type = "item", name = "kr-imersium-gear-wheel", amount = 4 },
			{ type = "item", name = "low-density-structure", amount = 1 },
		},
		results = { { type = "item", name = "kr-superior-transport-belt", amount = 1 } },
	},
	{
		type = "recipe",
		name = "kr-superior-underground-belt",
		category = "metallurgy",
		energy_required = 2,
		enabled = false,
		ingredients = {
			{ type = "item", name = "turbo-underground-belt", amount = 2 },
			{ type = "item", name = "kr-superior-transport-belt", amount = 40 },
			{ type = "item", name = "kr-imersium-gear-wheel", amount = 10 },
		},
		results = { { type = "item", name = "kr-superior-underground-belt", amount = 2 } },
	},
})
