data:extend({
	{
		type = "recipe",
		name = "kr-bio-processing-circuit",
		enabled = false,
		order = "b[circuits]-c[processing-circuit-bio]",
		icons = {
			{ icon = "__base__/graphics/icons/processing-unit.png" },
			{ icon = "__space-age__/graphics/icons/pentapod-egg.png", scale = 0.26, shift = { -8, -8 } },
		},
		category = "electronics",
		energy_required = 6,
		auto_recycle = false,
		ingredients = {
			{ type = "fluid", name = "sulfuric-acid", amount = 10 },
			{ type = "item", name = "advanced-circuit", amount = 4 },
			{ type = "item", name = "pentapod-egg", amount = 1 },
		},
		results = { { type = "item", name = "processing-unit", amount = 2 } },
		allow_productivity = true,
		hide_from_signal_gui = false,
	},
	{
		type = "recipe",
		name = "kr-automation-core",
		enabled = false,
		category = "electronics",
		energy_required = 2,
		ingredients = {
			{ type = "item", name = "iron-gear-wheel", amount = 4 },
			{ type = "item", name = "iron-stick", amount = 4 },
			{ type = "item", name = "copper-plate", amount = 6 },
		},
		results = { { type = "item", name = "kr-automation-core", amount = 2 } },
		allow_productivity = true,
	},
	{
		type = "recipe",
		name = "kr-blank-tech-card",
		enabled = false,
		category = "electronics",
		energy_required = 2,
		ingredients = {
			{ type = "item", name = "iron-plate", amount = 2 },
			{ type = "item", name = "copper-cable", amount = 2 },
		},
		results = { { type = "item", name = "kr-blank-tech-card", amount = 5 } },
		allow_productivity = true,
	},
	{
		type = "recipe",
		name = "kr-electronic-components",
		enabled = false,
		category = "electronics",
		energy_required = 4,
		ingredients = {
			{ type = "item", name = "kr-silicon", amount = 2 },
			{ type = "item", name = "plastic-bar", amount = 2 },
			{ type = "item", name = "kr-glass", amount = 2 },
		},
		results = { { type = "item", name = "kr-electronic-components", amount = 4 } },
		allow_productivity = true,
	},
	{
		type = "recipe",
		name = "kr-energy-control-unit",
		enabled = false,
		category = "electronics",
		energy_required = 10,
		ingredients = {
			{ type = "item", name = "low-density-structure", amount = 6 },
			{ type = "item", name = "kr-imersite-crystal", amount = 3 },
			{ type = "item", name = "kr-electronic-components", amount = 9 },
			{ type = "item", name = "kr-lithium-sulfur-battery", amount = 3 },
		},
		results = { { type = "item", name = "kr-energy-control-unit", amount = 1 } },
		allow_productivity = true,
	},
	{
		type = "recipe",
		name = "kr-electronic-circuit-wood",
		enabled = false,
		order = "b[circuits]-a[electronic-circuit-wood]",
		icons = {
			{ icon = "__Krastorio2Assets__/icons/items/electronic-circuit.png" },
			{ icon = "__base__/graphics/icons/wood.png", scale = 0.26, shift = { -8, -8 } },
		},
		energy_required = 2,
		category = "electronics",
		ingredients = {
			{ type = "item", name = "iron-plate", amount = 1 },
			{ type = "item", name = "wood", amount = 1 },
			{ type = "item", name = "copper-cable", amount = 4 },
		},
		results = { { type = "item", name = "electronic-circuit", amount = 2 } },
		allow_productivity = true,
		hide_from_signal_gui = false,
		auto_recycle = false,
	},
})
