data:extend({

	--rare metals

	{
		type = "recipe",
		name = "kr-molten-rare-metals-from-lava",
		category = "metallurgy",
		subgroup = "vulcanus-processes",
		order = "a[melting]-a[lava-c]",
		icon = "__k2so-assets__/icons/recipes/molten-rare-metals-from-lava.png",
		enabled = false,
		ingredients = {
			{ type = "item", name = "calcite", amount = 2, fluidbox_multiplier = 10 },
			{ type = "fluid", name = "lava", amount = 500, fluidbox_multiplier = 10 },
			{ type = "fluid", name = "kr-hydrogen-chloride", amount = 10, fluidbox_multiplier = 10 },
		},
		energy_required = 16,
		allow_decomposition = false,
		results = {
			{ type = "fluid", name = "kr-molten-rare-metals", amount = 100 },
			{ type = "fluid", name = "molten-iron", amount = 20 },
		},
		allow_productivity = true,
		main_product = "kr-molten-rare-metals",
	},
	{
		type = "recipe",
		name = "kr-molten-rare-metals",
		category = "metallurgy",
		subgroup = "vulcanus-processes",
		order = "a[melting]-c[molten-rare-metals]",
		icon = "__k2so-assets__/icons/recipes/melting-rare-metals.png",
		enabled = false,
		ingredients = {
			{ type = "item", name = "calcite", amount = 2, fluidbox_multiplier = 10 },
			{ type = "item", name = "kr-rare-metal-ore", amount = 50, fluidbox_multiplier = 10 },
		},
		energy_required = 32,
		allow_decomposition = false,
		results = {
			{ type = "fluid", name = "kr-molten-rare-metals", amount = 300 },
		},
		allow_productivity = true,
		always_show_products = true,
	},
	{
		type = "recipe",
		name = "kr-molten-enriched-rare-metals",
		category = "metallurgy",
		subgroup = "vulcanus-processes",
		order = "a[melting]-f[molten-rare-metals]",
		icon = "__k2so-assets__/icons/recipes/melting-enriched-rare-metals.png",
		enabled = false,
		ingredients = {
			{ type = "item", name = "calcite", amount = 2, fluidbox_multiplier = 10 },
			{ type = "item", name = "kr-enriched-rare-metals", amount = 40, fluidbox_multiplier = 10 },
		},
		energy_required = 24,
		allow_decomposition = false,
		results = {
			{ type = "fluid", name = "kr-molten-rare-metals", amount = 600 },
		},
		allow_productivity = true,
	},
	{
		type = "recipe",
		name = "kr-casting-rare-metals",
		category = "metallurgy",
		subgroup = "vulcanus-processes",
		order = "b[casting]-ca[casting-molten-rare-metals]",
		icons = {
			{ icon = "__Krastorio2Assets__/icons/items/rare-metals.png" },
			{ icon = "__k2so-assets__/icons/fluids/molten-rare-metals.png", scale = 0.35, shift = { 8, -8 } },
		},
		enabled = false,
		ingredients = {
			{ type = "fluid", name = "kr-molten-rare-metals", amount = 10, fluidbox_multiplier = 10 },
			{ type = "fluid", name = "water", amount = 10, fluidbox_multiplier = 10 },
		},
		energy_required = 1.6,
		allow_decomposition = false,
		results = {
			{ type = "item", name = "kr-rare-metals", amount = 1 },
			{
				type = "fluid",
				name = "kr-dirty-water",
				amount = 5,
				fluidbox_multiplier = 10,
				ignored_by_productivity = 5,
			},
		},
		allow_productivity = true,
		main_product = "kr-rare-metals",
	},

	--enriched melting

	{
		type = "recipe",
		name = "molten-enriched-copper",
		icon = "__k2so-assets__/icons/recipes/melting-enriched-copper.png",
		category = "metallurgy",
		subgroup = "vulcanus-processes",
		order = "a[melting]-e[molten-copper]",
		auto_recycle = false,
		show_amount_in_title = false,
		always_show_products = true,
		enabled = false,
		ingredients = {
			{ type = "item", name = "kr-enriched-copper", amount = 40 },
			{ type = "item", name = "calcite", amount = 1 },
		},
		energy_required = 24,
		results = {
			{ type = "fluid", name = "molten-copper", amount = 600 },
		},
		allow_productivity = true,
		hide_from_signal_gui = false,
		main_product = "molten-copper",
	},
	{
		type = "recipe",
		name = "molten-enriched-iron",
		icon = "__k2so-assets__/icons/recipes/melting-enriched-iron.png",
		category = "metallurgy",
		subgroup = "vulcanus-processes",
		order = "a[melting]-d[molten-iron]",
		auto_recycle = false,
		show_amount_in_title = false,
		always_show_products = true,
		enabled = false,
		ingredients = {
			{ type = "item", name = "kr-enriched-iron", amount = 40 },
			{ type = "item", name = "calcite", amount = 1 },
		},
		energy_required = 24,
		results = {
			{ type = "fluid", name = "molten-iron", amount = 600 },
		},
		allow_productivity = true,
		hide_from_signal_gui = false,
		main_product = "molten-iron",
	},

	--casting

	{
		type = "recipe",
		name = "kr-casting-iron-beam",
		category = "metallurgy",
		subgroup = "vulcanus-processes",
		order = "b[casting]-ec[casting-iron-beam]",
		localised_name = { "", { "recipe-name.casting" }, " ", { "item-name.kr-iron-beam" } },
		icons = {
			{ icon = "__Krastorio2Assets__/icons/items/iron-beam.png" },
			{ icon = "__space-age__/graphics/icons/fluid/molten-iron.png", scale = 0.33, shift = { 8, -8 } },
		},
		hide_from_signal_gui = false,
		enabled = false,
		ingredients = {
			{ type = "fluid", name = "molten-iron", amount = 20, fluidbox_multiplier = 10 },
		},
		energy_required = 1,
		allow_decomposition = false,
		results = { { type = "item", name = "kr-iron-beam", amount = 1 } },
		allow_productivity = true,
	},
	{
		type = "recipe",
		name = "kr-casting-steel-beam",
		category = "metallurgy",
		subgroup = "vulcanus-processes",
		order = "b[casting]-eb[casting-steel-beam]",
		localised_name = { "", { "recipe-name.casting" }, " ", { "item-name.kr-steel-beam" } },
		icons = {
			{ icon = "__Krastorio2Assets__/icons/items/steel-beam.png" },
			{ icon = "__space-age__/graphics/icons/fluid/molten-iron.png", scale = 0.33, shift = { 8, -8 } },
		},
		hide_from_signal_gui = false,
		enabled = false,
		ingredients = {
			{ type = "fluid", name = "molten-iron", amount = 40, fluidbox_multiplier = 10 },
		},
		energy_required = 1,
		allow_decomposition = false,
		results = { { type = "item", name = "kr-steel-beam", amount = 1 } },
		allow_productivity = true,
	},
	{
		type = "recipe",
		name = "kr-casting-steel-gear",
		category = "metallurgy",
		subgroup = "vulcanus-processes",
		order = "b[casting]-d[casting-steel-gear]",
		localised_name = { "", { "recipe-name.casting" }, " ", { "item-name.kr-steel-gear-wheel" } },
		icons = {
			{ icon = "__Krastorio2Assets__/icons/items/steel-gear-wheel.png" },
			{ icon = "__space-age__/graphics/icons/fluid/molten-iron.png", scale = 0.33, shift = { 8, -8 } },
		},
		hide_from_signal_gui = false,
		enabled = false,
		ingredients = {
			{ type = "fluid", name = "molten-iron", amount = 20, fluidbox_multiplier = 10 },
		},
		energy_required = 1,
		allow_decomposition = false,
		results = { { type = "item", name = "kr-steel-gear-wheel", amount = 1 } },
		allow_productivity = true,
	},
	{
		type = "recipe",
		name = "kr-casting-steel-pipe",
		category = "metallurgy",
		subgroup = "energy-pipe-distribution",
		order = "b[casting]-f[steel-pipe]",
		localised_name = { "", { "recipe-name.casting" }, " ", { "entity-name.kr-steel-pipe" } },
		icons = {
			{ icon = "__Krastorio2Assets__/icons/entities/steel-pipe.png", scale = 0.5, shift = { -8, 8 } },
			{ icon = "__space-age__/graphics/icons/fluid/molten-iron.png", scale = 0.5, shift = { 8, -8 } },
		},
		hide_from_signal_gui = false,
		enabled = false,
		ingredients = {
			{ type = "fluid", name = "molten-iron", amount = 20, fluidbox_multiplier = 10 },
		},
		energy_required = 1,
		allow_decomposition = false,
		results = { { type = "item", name = "kr-steel-pipe", amount = 1 } },
		allow_productivity = true,
	},
	{
		type = "recipe",
		name = "kr-casting-steel-pipe-to-ground",
		category = "metallurgy",
		subgroup = "energy-pipe-distribution",
		order = "b[casting]-g[steel-pipe-to-ground.png]",
		localised_name = { "", { "recipe-name.casting" }, " ", { "entity-name.kr-steel-pipe-to-ground" } },
		icons = {
			{ icon = "__Krastorio2Assets__/icons/entities/steel-pipe-to-ground.png", scale = 0.5, shift = { -8, 8 } },
			{ icon = "__space-age__/graphics/icons/fluid/molten-iron.png", scale = 0.5, shift = { 8, -8 } },
		},
		hide_from_signal_gui = false,
		enabled = false,
		ingredients = {
			{ type = "item", name = "kr-steel-pipe", amount = 10, fluidbox_multiplier = 10 },
			{ type = "fluid", name = "molten-iron", amount = 100, fluidbox_multiplier = 10 },
		},
		energy_required = 1,
		allow_decomposition = false,
		results = { { type = "item", name = "kr-steel-pipe-to-ground", amount = 2 } },
		allow_productivity = true,
	},
	{
		type = "recipe",
		name = "kr-refined-concrete-from-molten-iron",
		category = "metallurgy",
		subgroup = "vulcanus-processes",
		order = "b[casting]-ga[refined-concrete]",
		localised_name = { "", { "item-name.refined-concrete" }, " ", { "recipe-name.kr-from-molten-iron" } },
		icons = {
			{ icon = "__base__/graphics/icons/refined-concrete.png" },
			{ icon = "__space-age__/graphics/icons/fluid/molten-iron.png", scale = 0.33, shift = { 8, -8 } },
		},
		enabled = false,
		ingredients = {
			{ type = "item", name = "concrete", amount = 20, fluidbox_multiplier = 10 },
			{ type = "fluid", name = "molten-iron", amount = 100, fluidbox_multiplier = 10 },
			{ type = "fluid", name = "water", amount = 100, fluidbox_multiplier = 10 },
		},
		energy_required = 15,
		allow_decomposition = false,
		hide_from_signal_gui = false,
		results = { { type = "item", name = "refined-concrete", amount = 10 } },
		allow_productivity = true,
	},
	{
		type = "recipe",
		name = "kr-casting-imersium-plate",
		category = "metallurgy",
		subgroup = "vulcanus-processes",
		order = "b[casting]-cb[imersium-plate]",
		localised_name = { "", { "recipe-name.casting" }, " ", { "item-name.kr-imersium-plate" } },
		icons = {
			{ icon = "__Krastorio2Assets__/icons/items/imersium-plate.png" },
			{ icon = "__k2so-assets__/icons/fluids/molten-rare-metals.png", scale = 0.33, shift = { 8, -8 } },
		},
		hide_from_signal_gui = false,
		enabled = false,
		energy_required = 32,
		ingredients = {
			{ type = "fluid", name = "kr-molten-rare-metals", amount = 60, fluidbox_multiplier = 10 },
			{ type = "item", name = "kr-imersite-powder", amount = 9 },
		},
		results = { { type = "item", name = "kr-imersium-plate", amount = 3 } },
		allow_decomposition = false,
		allow_productivity = true,
	},
	{
		type = "recipe",
		name = "kr-casting-imersium-beam",
		category = "metallurgy",
		subgroup = "vulcanus-processes",
		order = "b[casting]-ec[imersium-beam]",
		localised_name = { "", { "recipe-name.casting" }, " ", { "item-name.kr-imersium-beam" } },
		icons = {
			{ icon = "__Krastorio2Assets__/icons/items/imersium-beam.png" },
			{ icon = "__k2so-assets__/icons/fluids/molten-rare-metals.png", scale = 0.33, shift = { 8, -8 } },
		},
		hide_from_signal_gui = false,
		enabled = false,
		energy_required = 12,
		ingredients = {
			{ type = "fluid", name = "kr-molten-rare-metals", amount = 40, fluidbox_multiplier = 10 },
			{ type = "item", name = "kr-imersite-powder", amount = 6 },
		},
		results = { { type = "item", name = "kr-imersium-beam", amount = 1 } },
		allow_decomposition = false,
		allow_productivity = true,
	},
	{
		type = "recipe",
		name = "kr-casting-imersium-gear-wheel",
		category = "metallurgy",
		subgroup = "vulcanus-processes",
		order = "b[casting]-da[imersium-gear-wheel]",
		localised_name = { "", { "recipe-name.casting" }, " ", { "item-name.kr-imersium-gear-wheel" } },
		icons = {
			{ icon = "__Krastorio2Assets__/icons/items/imersium-gear-wheel.png" },
			{ icon = "__k2so-assets__/icons/fluids/molten-rare-metals.png", scale = 0.33, shift = { 8, -8 } },
		},
		hide_from_signal_gui = false,
		enabled = false,
		energy_required = 2,
		ingredients = {
			{ type = "fluid", name = "kr-molten-rare-metals", amount = 20, fluidbox_multiplier = 10 },
			{ type = "item", name = "kr-imersite-powder", amount = 3 },
		},
		results = { { type = "item", name = "kr-imersium-gear-wheel", amount = 1 } },
		allow_decomposition = false,
		allow_productivity = true,
	},
})
