data:extend({
	{
		type = "recipe",
		name = "kr-spoilage-decomposition",
		icons = {
			{ icon = "__Krastorio2Assets__/icons/fluids/biomethanol.png" },
			{ icon = "__space-age__/graphics/icons/spoilage.png", scale = 0.5, shift = { -12, -12 } },
		},
		icon_size = 128,
		subgroup = "agriculture-processes",
		order = "a1[organics]-a[compost]",
		enabled = false,
		categories = { "organic" },
		allow_productivity = true,
		energy_required = 30,
		show_amount_in_title = false,
		ingredients = {
			{ type = "item", name = "spoilage", amount = 30 },
			{ type = "item", name = "bioflux", amount = 2 },
		},
		results = {
			{ type = "fluid", name = "kr-biomethanol", amount = 300 },
		},
	},
	{
		type = "recipe",
		name = "kr-bio-processing-circuit",
		enabled = false,
		subgroup = "agriculture-products",
		order = "a[organic]-i[processing-circuit-bio]",
		icons = {
			{ icon = "__base__/graphics/icons/processing-unit.png" },
			{ icon = "__space-age__/graphics/icons/pentapod-egg.png", scale = 0.33, shift = { -8, -8 } },
		},
		categories = { "organic" },
		energy_required = 4,
		auto_recycle = false,
		ingredients = {
			{ type = "fluid", name = "sulfuric-acid", amount = 10 },
			{ type = "item", name = "advanced-circuit", amount = 6 },
			{ type = "item", name = "pentapod-egg", amount = 1 },
		},
		results = { { type = "item", name = "processing-unit", amount = 4 } },
		allow_productivity = true,
		hide_from_signal_gui = false,
	},
	{
		type = "recipe",
		name = "kr-biter-egg-upcycling",
		icons = {
			{ icon = "__space-age__/graphics/icons/biter-egg.png" },
			{ icon = "__core__/graphics/icons/any-quality.png", scale = 0.25, shift = { 8, -8 } },
		},
		icon_size = 128,
		subgroup = "nauvis-agriculture",
		order = "b[nauvis-agriculture]-b1[biter-upcycling]",
		enabled = false,
		categories = { "kr-bioprocessing" },
		allow_productivity = false,
		energy_required = 15,
		show_amount_in_title = false,
		ingredients = {
			{ type = "item", name = "biter-egg", amount = 1 },
			{ type = "item", name = "bioflux", amount = 2, quality_max = "normal" },
		},
		results = {
			{
				type = "item",
				name = "biter-egg",
				amount = 1,
				shared_probability = { min = 0.5, max = 0.65 },
				quality_change = -1,
			},
			{
				type = "item",
				name = "biter-egg",
				amount = 1,
				shared_probability = { min = 0, max = 0.5 },
			},
			{
				type = "item",
				name = "biter-egg",
				amount = 1,
				shared_probability = { min = 0.65, max = 0.95 },
				quality_change = 1,
			},
			{
				type = "item",
				name = "biter-egg",
				amount = 1,
				shared_probability = { min = 0.95, max = 1 },
				quality_change = 2,
			},
		},
	},
})
