local recipe = data.raw.recipe
recipe["kr-copper-plate-from-enriched-copper"].auto_recycle = false
recipe["kr-iron-plate-from-enriched-iron"].auto_recycle = false
recipe["kr-rare-metals-from-enriched-rare-metals"].auto_recycle = false
recipe["kr-rare-metals"].auto_recycle = false
recipe["kr-silicon"].auto_recycle = false
recipe["kr-glass"].auto_recycle = false
recipe["kr-quartz"].auto_recycle = false
recipe["kr-coke"].auto_recycle = false
recipe["kr-imersium-plate"].auto_recycle = false
recipe["kr-enriched-iron"].auto_recycle = false
recipe["kr-enriched-copper"].auto_recycle = false
recipe["kr-enriched-rare-metals"].auto_recycle = false
recipe["kr-imersium-plate"].auto_recycle = false
recipe["kr-rocket-fuel-with-ammonia"].auto_recycle = false
recipe["rocket-fuel"].auto_recycle = false
recipe["kr-rocket-fuel-with-hydrogen-chloride"].auto_recycle = false
recipe["kr-charged-matter-stabilizer"].auto_recycle = false
