local data_util = require("data-util")

--guns
data_util.set_weight("kr-impulse-rifle", 100)
data_util.set_weight("kr-heavy-rocket-launcher", 200)

--ammo
data_util.set_weight("kr-imersite-rounds-magazine", 5)
data_util.set_weight("kr-impulse-rifle-ammo", 10)
data_util.set_weight("kr-heavy-rocket", 40)
data_util.set_weight("kr-basic-railgun-shell", 40)
data_util.set_weight("kr-explosive-railgun-shell", 40)
data_util.set_weight("kr-explosive-turret-rocket", 40)
data_util.set_weight("kr-antimatter-railgun-shell", 80)
data_util.set_weight("atomic-bomb", 1000)
data_util.set_weight("kr-nuclear-turret-rocket", 1000)
data_util.set_weight("kr-nuclear-artillery-shell", 1000)
data_util.set_weight("kr-antimatter-rocket", 1000)
data_util.set_weight("kr-antimatter-turret-rocket", 1000)
data_util.set_weight("kr-antimatter-artillery-shell", 1000)

--capsules
data_util.set_weight("cliff-explosives", 5)
data_util.set_weight("kr-biter-virus", 10)
data_util.set_weight("kr-first-aid-kit", 20)

--tech card
data_util.set_weight("kr-blank-tech-card", 1)
data_util.set_weight("kr-biter-research-data", 1)
data_util.set_weight("kr-space-research-data", 1)
data_util.set_weight("kr-matter-research-data", 1)
data_util.set_weight("kr-matter-tech-card", 1)
data_util.set_weight("kr-advanced-tech-card", 1)
data_util.set_weight("kr-singularity-tech-card", 1)

--item
data_util.set_weight("kr-rare-metals", 1)
data_util.set_weight("kr-enriched-iron", 1)
data_util.set_weight("kr-enriched-copper", 1)
data_util.set_weight("kr-enriched-rare-metals", 1)
data_util.set_weight("kr-lithium", 1)
data_util.set_weight("kr-lithium-chloride", 1)
data_util.set_weight("kr-imersite-powder", 1)
data_util.set_weight("kr-imersite-crystal", 1)
data_util.set_weight("kr-sand", 1)
data_util.set_weight("kr-glass", 1)
data_util.set_weight("kr-quartz", 1)
data_util.set_weight("kr-silicon", 1)
data_util.set_weight("kr-coke", 1)
data_util.set_weight("kr-biomass", 2.5)
data_util.set_weight("kr-fertilizer", 2.5)
data_util.set_weight("kr-automation-core", 2.5)
data_util.set_weight("kr-electronic-components", 2.5)
data_util.set_weight("kr-fuel", 5)
data_util.set_weight("kr-inserter-parts", 5)
data_util.set_weight("kr-biofuel", 5)
data_util.set_weight("kr-advanced-fuel", 5)
data_util.set_weight("kr-iron-beam", 5)
data_util.set_weight("kr-steel-gear-wheel", 5)
data_util.set_weight("kr-steel-beam", 5)
data_util.set_weight("kr-imersium-plate", 5)
data_util.set_weight("kr-imersium-gear-wheel", 5)
data_util.set_weight("kr-imersium-beam", 5)
data_util.set_weight("kr-lithium-sulfur-battery", 5)
data_util.set_weight("kr-ai-core", 5)
data_util.set_weight("kr-pollution-filter", 5)
data_util.set_weight("kr-used-pollution-filter", 5)
data_util.set_weight("kr-tritium", 5)
data_util.set_weight("uranium-235", 10)
data_util.set_weight("uranium-238", 10)
data_util.set_weight("kr-energy-control-unit", 10)
data_util.set_weight("kr-matter-stabilizer", 10)
data_util.set_weight("kr-charged-matter-stabilizer", 10)
data_util.set_weight("kr-matter-cube", 20)
data_util.set_weight("kr-dt-fuel-cell", 100)
data_util.set_weight("kr-empty-dt-fuel-cell", 100)
data_util.set_weight("kr-empty-antimatter-fuel-cell", 100)
data_util.set_weight("kr-charged-antimatter-fuel-cell", 100)
data_util.set_weight("kr-teleportation-gps-module", 100)

--buildings
data_util.set_weight("stone-wall", 5)
data_util.set_weight("solar-panel", 40)
data_util.set_weight("pumpjack", 50)
data_util.set_weight("beacon", 50)
data_util.set_weight("kr-active-provider-strongbox", 20)
data_util.set_weight("kr-active-provider-warehouse", 100)
data_util.set_weight("kr-passive-provider-strongbox", 20)
data_util.set_weight("kr-passive-provider-warehouse", 100)
data_util.set_weight("kr-buffer-strongbox", 20)
data_util.set_weight("kr-buffer-warehouse", 100)
data_util.set_weight("kr-requester-strongbox", 20)
data_util.set_weight("kr-requester-warehouse", 100)
data_util.set_weight("kr-storage-strongbox", 20)
data_util.set_weight("kr-storage-warehouse", 100)
data_util.set_weight("kr-strongbox", 20)
data_util.set_weight("kr-warehouse", 100)
data_util.set_weight("kr-advanced-assembling-machine", 100)
data_util.set_weight("kr-advanced-chemical-plant", 200)
data_util.set_weight("kr-advanced-furnace", 500)
data_util.set_weight("kr-advanced-lab", 100)
data_util.set_weight("kr-advanced-radar", 40)
data_util.set_weight("kr-advanced-solar-panel", 40)
data_util.set_weight("kr-advanced-steam-turbine", 200)
data_util.set_weight("kr-antimatter-reactor", 1000)
data_util.set_weight("kr-atmospheric-condenser", 40)
data_util.set_weight("kr-big-roboport", 200)
data_util.set_weight("kr-big-storage-tank", 40)
data_util.set_weight("kr-bio-lab", 100)
data_util.set_weight("kr-crusher", 40)
data_util.set_weight("kr-electric-mining-drill-mk2", 20)
data_util.set_weight("kr-electrolysis-plant", 40)
data_util.set_weight("kr-energy-storage", 100)
data_util.set_weight("kr-superior-loader", 20)
data_util.set_weight("kr-express-loader", 20)
data_util.set_weight("kr-fast-loader", 20)
data_util.set_weight("kr-loader", 20)
data_util.set_weight("kr-filtration-plant", 40)
data_util.set_weight("kr-fuel-refinery", 40)
data_util.set_weight("kr-fusion-reactor", 1000)
data_util.set_weight("kr-greenhouse", 100)
data_util.set_weight("kr-huge-storage-tank", 100)
data_util.set_weight("kr-laser-artillery-turret", 200)
data_util.set_weight("kr-matter-associator", 200)
data_util.set_weight("kr-matter-plant", 200)
data_util.set_weight("kr-planetary-teleporter", 40)
data_util.set_weight("kr-quarry-drill", 100)
data_util.set_weight("kr-railgun-turret", 200)
data_util.set_weight("kr-research-server", 40)
data_util.set_weight("kr-rocket-turret", 40)
data_util.set_weight("kr-singularity-beacon", 40)
data_util.set_weight("kr-singularity-lab", 1000)
data_util.set_weight("kr-small-roboport", 100)
data_util.set_weight("kr-stabilizer-charging-station", 100)
data_util.set_weight("kr-steel-pipe-to-ground", 20)
data_util.set_weight("kr-steel-pump", 20)
data_util.set_weight("kr-superior-inserter", 20)
data_util.set_weight("kr-superior-long-inserter", 20)
data_util.set_weight("kr-superior-splitter", 40)
data_util.set_weight("kr-superior-substation", 40)
data_util.set_weight("kr-superior-transport-belt", 20)
data_util.set_weight("kr-superior-underground-belt", 40)
data_util.set_weight("kr-tesla-coil", 100)
data_util.set_weight("kr-quantum-computer", 100)
-- surface_conditions = {
--   { property = "pressure", min = 0.1, }
-- }
