data.raw.item["kr-space-research-data"].stack_size = 1000
data:extend({
	{
		type = "item",
		name = "kr-electromagnetic-research-data",
		icon = "__k2so-assets__/icons/cards/electromagnetic-research-data.png",
		subgroup = "science-pack",
		order = "a05[electromagnetic-research-data]",
		stack_size = 200,
		weight = 1 * kg,
		default_import_location = "fulgora",
	},
	{
		type = "item",
		name = "kr-metallurgic-research-data",
		icon = "__k2so-assets__/icons/cards/metallurgic-research-data.png",
		subgroup = "science-pack",
		order = "a04[metallurgic-research-data]",
		stack_size = 200,
		weight = 1 * kg,
		default_import_location = "vulcanus",
	},
	{
		type = "item",
		name = "kr-agricultural-research-data",
		icon = "__k2so-assets__/icons/cards/agricultural-research-data.png",
		subgroup = "science-pack",
		order = "a05[agricultural-research-data]",
		stack_size = 200,
		weight = 1 * kg,
		spoil_result = "spoilage",
		spoil_ticks = 54000,
		default_import_location = "gleba",
	},
	{
		type = "item",
		name = "kr-cryogenic-research-data",
		icon = "__k2so-assets__/icons/cards/cryogenic-research-data.png",
		subgroup = "science-pack",
		order = "a07[cryogenic-research-data]",
		stack_size = 200,
		weight = 1 * kg,
		default_import_location = "aquilo",
	},
	{
		type = "item",
		name = "kr-promethium-research-data",
		icon = "__k2so-assets__/icons/cards/promethium-research-data.png",
		subgroup = "science-pack",
		order = "a08[promethium-research-data]",
		stack_size = 200,
		weight = 1 * kg,
		default_import_location = "aquilo",
	},
})
