data.raw["assembling-machine"]["kr-advanced-assembling-machine"].crafting_categories = {
	"crafting",
	"advanced-crafting",
	"crafting-with-fluid",
	"electronics",
	"electronics-with-fluid",
	"kr-smelting-crafting",
	"pressing",
	"metallurgy-or-assembling",
	"organic-or-hand-crafting",
	"organic-or-assembling",
	"electronics-or-assembling",
	"cryogenics-or-assembling",
	"crafting-with-fluid-or-metallurgy",
}
